model:
    pretrained_model_name_or_path: /kaggle/input/deberta-v3-large-hf-weights
    peft_model_id: /kaggle/input/tempx1/checkpoint-6256
    backbone_name: deberta
    device_map: cuda
    load_in_4bit: False
    sliding_window_config:
        use_sliding_window: True
        window_size: 512
        inner_size: 384
        n_tokens: 64
    span_pooling_config:
        use_span_pooling: True
        pooling_name: attention
        in_features: 1024
        hidden_dim: 1024
        span_type: sentence
        ignored_span_id: -100
    final_pooling_config: 
        pooling_name: mean
    loss_weights: [0.21, 0.16, 0.10, 0.16, 0.21, 0.16]

data:
    eval_file: /kaggle/input/feedback-prize-english-language-learning/test.csv
    max_len: 2048
    text_column: full_text
    label_column_names: [cohesion, syntax, vocabulary, phraseology, grammar, conventions]
